name: manylinux2014
on:
  workflow_dispatch
#  schedule:
#    - cron: '*/20 * * * *'


env:
  TZ: Asia/Shanghai


jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get current date
        id: date
        run: |
          echo "::set-output name=today::$(date +'%Y-%m-%d')"
          echo  $(date)

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKHUB_USER_ZKP }}
          password: ${{ secrets.DOCKHUB_SECRET_ZKP }}

      - name: run py
        run: python to_dockerhub.py

